/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tacondeoro;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author usutarde
 */
public class VentanaClientes extends javax.swing.JFrame {
    Connection c = null;

    DefaultListModel dlmArticulos;
    DefaultListModel dlmLineasPedido;

    /**
     * Creates new form Prueba
     */
    public VentanaClientes() {
        initComponents();
        
        dlmArticulos = new DefaultListModel();
        dlmLineasPedido = new DefaultListModel();
        lst_Articulos.setModel(dlmArticulos);
        lst_lineasPedido.setModel(dlmLineasPedido);
        
        DatabaseConnection db = new DatabaseConnection();
        c = db.getConexion();

        mostrarZapatos();
        mostrarBolsos();
        mostrarComplementos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cb_CampanaOtoñoInvierno = new javax.swing.JCheckBox();
        cb_CampanaPrimaveraVerano = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_Articulos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btt_añadirAlCarrito = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lst_lineasPedido = new javax.swing.JList<>();
        btt_tramitarPedido = new javax.swing.JButton();
        btt_borrarDelCarrito = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_Cantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_Bolsos = new javax.swing.JCheckBox();
        cb_Complementos = new javax.swing.JCheckBox();
        cb_Zapatos = new javax.swing.JCheckBox();
        tf_Talla = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mb_Pedidos = new javax.swing.JMenu();
        mi_gestionarPedidos = new javax.swing.JMenuItem();
        mb_Menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_CampanaOtoñoInvierno.setText("Otoño/Invierno");
        cb_CampanaOtoñoInvierno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CampanaOtoñoInviernoActionPerformed(evt);
            }
        });

        cb_CampanaPrimaveraVerano.setText("Primavera/Verano");
        cb_CampanaPrimaveraVerano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CampanaPrimaveraVeranoActionPerformed(evt);
            }
        });

        lst_Articulos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_Articulos);

        jLabel1.setText("ARTICULOS");

        jLabel5.setText("CANTIDAD");

        btt_añadirAlCarrito.setText("AÑADIR AL CARRITO");
        btt_añadirAlCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_añadirAlCarritoActionPerformed(evt);
            }
        });

        lst_lineasPedido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Linea Pedido 1", "Linea Pedido 2", "Linea Pedido 3", "Linea Pedido 4", "Linea Pedido 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lst_lineasPedido);

        btt_tramitarPedido.setText("TRAMITAR PEDIDO");
        btt_tramitarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_tramitarPedidoActionPerformed(evt);
            }
        });

        btt_borrarDelCarrito.setText("ELIMINAR DEL CARRITO");
        btt_borrarDelCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_borrarDelCarritoActionPerformed(evt);
            }
        });

        jLabel6.setText("TALLA");

        jLabel2.setText("CARRITO");

        jLabel3.setText("TOTAL DE PEDIDO");

        cb_Bolsos.setText("Bolsos");
        cb_Bolsos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_BolsosActionPerformed(evt);
            }
        });

        cb_Complementos.setText("Complementos");
        cb_Complementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ComplementosActionPerformed(evt);
            }
        });

        cb_Zapatos.setText("Zapatos");
        cb_Zapatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ZapatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_CampanaOtoñoInvierno)
                                    .addComponent(cb_CampanaPrimaveraVerano))
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_Complementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_Bolsos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_Zapatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btt_borrarDelCarrito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btt_añadirAlCarrito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(43, 43, 43))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_Cantidad)
                                            .addComponent(tf_Talla))
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                            .addComponent(btt_tramitarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(tf_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(tf_Talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btt_añadirAlCarrito)
                                        .addGap(18, 18, 18)
                                        .addComponent(btt_borrarDelCarrito)
                                        .addGap(137, 137, 137))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane5)
                                        .addGap(18, 18, 18)))
                                .addComponent(btt_tramitarPedido))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cb_CampanaPrimaveraVerano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_CampanaOtoñoInvierno)
                        .addGap(49, 49, 49)
                        .addComponent(cb_Zapatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_Bolsos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_Complementos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mb_Pedidos.setText("PEDIDOS");

        mi_gestionarPedidos.setText("Gestionar Pedidos");
        mb_Pedidos.add(mi_gestionarPedidos);

        jMenuBar1.add(mb_Pedidos);

        mb_Menu.setText("MENU");

        jMenuItem1.setText("Volver al Menu");
        mb_Menu.add(jMenuItem1);

        jMenuBar1.add(mb_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 19, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_borrarDelCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_borrarDelCarritoActionPerformed
        
    }//GEN-LAST:event_btt_borrarDelCarritoActionPerformed

    private void btt_tramitarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_tramitarPedidoActionPerformed
        Date fecha = new Date();
        if(lst_lineasPedido.getLastVisibleIndex()==-1){
            JOptionPane.showMessageDialog(null, "Para tramitar pedido tiene que añadir articulos en la cesta");
        }else if(lst_lineasPedido.getLastVisibleIndex()>-1){
            
            ArrayList <LineaPedido> lineasDePedido = null;
            for (int i = 0; i < dlmLineasPedido.getSize(); i++) {
                lineasDePedido.add(i,(LineaPedido) dlmLineasPedido.getElementAt(i));
            }
            System.out.println(lineasDePedido);
            Pedido a = new Pedido(fecha, Double.parseDouble(tf_total.getText()), lineasDePedido);
            //Esto peta ns porq
            //Esto peta ns porq
            //Esto peta ns porq
        }
    }//GEN-LAST:event_btt_tramitarPedidoActionPerformed

    private void cb_CampanaPrimaveraVeranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CampanaPrimaveraVeranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CampanaPrimaveraVeranoActionPerformed

    private void cb_CampanaOtoñoInviernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CampanaOtoñoInviernoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CampanaOtoñoInviernoActionPerformed

    private void btt_añadirAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_añadirAlCarritoActionPerformed
        
    }//GEN-LAST:event_btt_añadirAlCarritoActionPerformed

    private void cb_ZapatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ZapatosActionPerformed
        // TODO add your handling code here:
        comprobarCheckboxes();
    }//GEN-LAST:event_cb_ZapatosActionPerformed

    private void cb_BolsosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_BolsosActionPerformed
        // TODO add your handling code here:
        comprobarCheckboxes();
    }//GEN-LAST:event_cb_BolsosActionPerformed

    private void cb_ComplementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ComplementosActionPerformed
        // TODO add your handling code here:
        comprobarCheckboxes();
    }//GEN-LAST:event_cb_ComplementosActionPerformed

    private void comprobarCheckboxes() {
        if (!cb_Zapatos.isSelected() && !cb_Bolsos.isSelected() && !cb_Complementos.isSelected()) {
            dlmArticulos.clear();
            mostrarZapatos();
            mostrarBolsos();
            mostrarComplementos();
            lst_Articulos.updateUI();
        }

        if (cb_Zapatos.isSelected() && cb_Bolsos.isSelected() && cb_Complementos.isSelected()) {
            dlmArticulos.clear();
            mostrarZapatos();
            mostrarBolsos();
            mostrarComplementos();
            lst_Articulos.updateUI();
        }
        
        if (cb_Zapatos.isSelected() && cb_Bolsos.isSelected() && !cb_Complementos.isSelected()) {
            dlmArticulos.clear();
            mostrarZapatos();
            mostrarBolsos();
            lst_Articulos.updateUI();
        }
        
        if (cb_Zapatos.isSelected() && cb_Complementos.isSelected() && !cb_Bolsos.isSelected()) {
            dlmArticulos.clear();
            mostrarZapatos();
            mostrarComplementos();
            lst_Articulos.updateUI();
        }
        
        if (cb_Bolsos.isSelected() && cb_Complementos.isSelected() && !cb_Zapatos.isSelected()) {
            dlmArticulos.clear();
            mostrarBolsos();
            mostrarComplementos();
            lst_Articulos.updateUI();
        }

        if (cb_Zapatos.isSelected() && !cb_Bolsos.isSelected() && !cb_Complementos.isSelected()) {
            dlmArticulos.clear();
            mostrarZapatos();
            lst_Articulos.updateUI();
        }

        if (cb_Bolsos.isSelected() && !cb_Zapatos.isSelected() && !cb_Complementos.isSelected()) {
            dlmArticulos.clear();
            mostrarBolsos();
            lst_Articulos.updateUI();
        }

        if (cb_Complementos.isSelected() && !cb_Zapatos.isSelected() && !cb_Bolsos.isSelected()) {
            dlmArticulos.clear();
            mostrarComplementos();
            lst_Articulos.updateUI();
        }
    }

    private void mostrarBolsos() {
        Statement s = null;
        ResultSet rs = null;

        try {
            s = c.createStatement();
            rs = s.executeQuery("select * from articulos;");
            while (rs.next()) {
                if (rs.getString(8).equalsIgnoreCase("bolso")) {
                    Bolso bo = new Bolso();
                    bo.setIdArticulo(rs.getInt(1));
                    bo.setNombre(rs.getString(2));
                    bo.setDescripcion(rs.getString(4));
                    bo.setMaterial(rs.getString(5));
                    bo.setPrecio(rs.getFloat(3));
                    bo.setStock(rs.getInt(6));
                    bo.setFotografia(rs.getString(7));
                    bo.setTipo(rs.getString(11));
                    dlmArticulos.addElement(bo);
                }
            }
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }
    
    private void mostrarZapatos() {
        Statement s = null;
        ResultSet rs = null;

        try {
            s = c.createStatement();
            rs = s.executeQuery("select * from articulos;");
            while (rs.next()) {
                if (rs.getString(8).equalsIgnoreCase("zapato")) {
                    Zapato za = new Zapato();
                    za.setIdArticulo(rs.getInt(1));
                    za.setNombre(rs.getString(2));
                    za.setDescripcion(rs.getString(4));
                    za.setMaterial(rs.getString(5));
                    za.setPrecio(rs.getFloat(3));
                    za.setStock(rs.getInt(6));
                    za.setFotografia(rs.getString(7));
                    za.setNumero(rs.getFloat(10));
                    za.setTipo(rs.getString(9));
                    dlmArticulos.addElement(za);
                }
            }
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }
    
    private void mostrarComplementos() {
        Statement s = null;
        ResultSet rs = null;

        try {
            s = c.createStatement();
            rs = s.executeQuery("select * from articulos;");
            while (rs.next()) {
                if (rs.getString(8).equalsIgnoreCase("complemento")) {
                    Complemento co = new Complemento();
                    co.setIdArticulo(rs.getInt(1));
                    co.setNombre(rs.getString(2));
                    co.setDescripcion(rs.getString(4));
                    co.setMaterial(rs.getString(5));
                    co.setPrecio(rs.getFloat(3));
                    co.setStock(rs.getInt(6));
                    co.setFotografia(rs.getString(7));
                    co.setTallaComplemento(rs.getInt(12));
                    dlmArticulos.addElement(co);
                }
            }
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_añadirAlCarrito;
    private javax.swing.JButton btt_borrarDelCarrito;
    private javax.swing.JButton btt_tramitarPedido;
    private javax.swing.JCheckBox cb_Bolsos;
    private javax.swing.JCheckBox cb_CampanaOtoñoInvierno;
    private javax.swing.JCheckBox cb_CampanaPrimaveraVerano;
    private javax.swing.JCheckBox cb_Complementos;
    private javax.swing.JCheckBox cb_Zapatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> lst_Articulos;
    private javax.swing.JList<String> lst_lineasPedido;
    private javax.swing.JMenu mb_Menu;
    private javax.swing.JMenu mb_Pedidos;
    private javax.swing.JMenuItem mi_gestionarPedidos;
    private javax.swing.JTextField tf_Cantidad;
    private javax.swing.JTextField tf_Talla;
    private javax.swing.JTextField tf_total;
    // End of variables declaration//GEN-END:variables
}
