/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tacondeoro;

/**
 *
 * @author usutarde
 */
public class VentanaClienteBuena extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    public VentanaClienteBuena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cb_CampanaOtoñoInvierno = new javax.swing.JCheckBox();
        cb_CampanaPrimaveraVerano = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_Articulos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        mn_MenuDesplegableCantidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btt_añadirAlCarrito = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lst_lineasPedido = new javax.swing.JList<>();
        btt_tramitarPedido = new javax.swing.JButton();
        cb_Zapatos = new javax.swing.JCheckBox();
        cb_Complementos = new javax.swing.JCheckBox();
        cb_Bolsos = new javax.swing.JCheckBox();
        btt_borrarDelCarrito = new javax.swing.JButton();
        tf_Talla = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mb_Pedidos = new javax.swing.JMenu();
        mi_gestionarPedidos = new javax.swing.JMenuItem();
        mb_Menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_CampanaOtoñoInvierno.setText("Otoño/Invierno");
        cb_CampanaOtoñoInvierno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CampanaOtoñoInviernoActionPerformed(evt);
            }
        });

        cb_CampanaPrimaveraVerano.setText("Primavera/Verano");
        cb_CampanaPrimaveraVerano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CampanaPrimaveraVeranoActionPerformed(evt);
            }
        });

        lst_Articulos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_Articulos);

        jLabel1.setText("ARTICULOS");

        mn_MenuDesplegableCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4" }));
        mn_MenuDesplegableCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_MenuDesplegableCantidadActionPerformed(evt);
            }
        });

        jLabel5.setText("CANTIDAD");

        btt_añadirAlCarrito.setText("AÑADIR AL CARRITO");
        btt_añadirAlCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_añadirAlCarritoActionPerformed(evt);
            }
        });

        lst_lineasPedido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Linea Pedido 1", "Linea Pedido 2", "Linea Pedido 3", "Linea Pedido 4", "Linea Pedido 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lst_lineasPedido);

        btt_tramitarPedido.setText("TRAMITAR PEDIDO");
        btt_tramitarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_tramitarPedidoActionPerformed(evt);
            }
        });

        cb_Zapatos.setText("Zapatos");
        cb_Zapatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ZapatosActionPerformed(evt);
            }
        });

        cb_Complementos.setText("Complementos");
        cb_Complementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ComplementosActionPerformed(evt);
            }
        });

        cb_Bolsos.setText("Bolsos");
        cb_Bolsos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_BolsosActionPerformed(evt);
            }
        });

        btt_borrarDelCarrito.setText("ELIMINAR DEL CARRITO");
        btt_borrarDelCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_borrarDelCarritoActionPerformed(evt);
            }
        });

        tf_Talla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TallaActionPerformed(evt);
            }
        });

        jLabel6.setText("TALLA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_CampanaOtoñoInvierno)
                            .addComponent(cb_CampanaPrimaveraVerano))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_Complementos)
                            .addComponent(cb_Bolsos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_Zapatos, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(28, 28, 28)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt_borrarDelCarrito)
                    .addComponent(btt_tramitarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btt_añadirAlCarrito)
                        .addGap(105, 105, 105)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(mn_MenuDesplegableCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tf_Talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_Talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btt_añadirAlCarrito)
                            .addComponent(mn_MenuDesplegableCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(btt_borrarDelCarrito)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btt_tramitarPedido))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(cb_CampanaPrimaveraVerano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_CampanaOtoñoInvierno)
                .addGap(49, 49, 49)
                .addComponent(cb_Zapatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_Bolsos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_Complementos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mb_Pedidos.setText("PEDIDOS");

        mi_gestionarPedidos.setText("Gestionar Pedidos");
        mb_Pedidos.add(mi_gestionarPedidos);

        jMenuBar1.add(mb_Pedidos);

        mb_Menu.setText("MENU");

        jMenuItem1.setText("Volver al Menu");
        mb_Menu.add(jMenuItem1);

        jMenuBar1.add(mb_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_borrarDelCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_borrarDelCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btt_borrarDelCarritoActionPerformed

    private void cb_BolsosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_BolsosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_BolsosActionPerformed

    private void cb_ComplementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ComplementosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_ComplementosActionPerformed

    private void cb_ZapatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ZapatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_ZapatosActionPerformed

    private void btt_tramitarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_tramitarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btt_tramitarPedidoActionPerformed

    private void mn_MenuDesplegableCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_MenuDesplegableCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_MenuDesplegableCantidadActionPerformed

    private void cb_CampanaPrimaveraVeranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CampanaPrimaveraVeranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CampanaPrimaveraVeranoActionPerformed

    private void cb_CampanaOtoñoInviernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CampanaOtoñoInviernoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CampanaOtoñoInviernoActionPerformed

    private void btt_añadirAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_añadirAlCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btt_añadirAlCarritoActionPerformed

    private void tf_TallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClienteBuena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClienteBuena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClienteBuena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClienteBuena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClienteBuena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_añadirAlCarrito;
    private javax.swing.JButton btt_borrarDelCarrito;
    private javax.swing.JButton btt_tramitarPedido;
    private javax.swing.JCheckBox cb_Bolsos;
    private javax.swing.JCheckBox cb_CampanaOtoñoInvierno;
    private javax.swing.JCheckBox cb_CampanaPrimaveraVerano;
    private javax.swing.JCheckBox cb_Complementos;
    private javax.swing.JCheckBox cb_Zapatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> lst_Articulos;
    private javax.swing.JList<String> lst_lineasPedido;
    private javax.swing.JMenu mb_Menu;
    private javax.swing.JMenu mb_Pedidos;
    private javax.swing.JMenuItem mi_gestionarPedidos;
    private javax.swing.JComboBox<String> mn_MenuDesplegableCantidad;
    private javax.swing.JTextField tf_Talla;
    // End of variables declaration//GEN-END:variables
}
