/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tacondeoro;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Arturo
 */
public class VentanaPagoPedido extends javax.swing.JDialog {
    private VentanaClientes padre = null;
    DefaultListModel dlmCestaDefinitiva;
    DefaultListModel dlmTarjetas;
    private static Socio usuario;

    /**
     * Creates new form VentanaComprobarCuartos
     */
    public VentanaPagoPedido(java.awt.Frame parent, boolean modal, Socio socio) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        padre = (VentanaClientes) parent;
        dlmCestaDefinitiva = new DefaultListModel();
        dlmTarjetas = new DefaultListModel();
        lst_CestaDefinitiva.setModel(dlmCestaDefinitiva);
        lst_TarjetasDisponibles.setModel(dlmTarjetas);
        usuario = socio;
        tf_socioCliente.setText(usuario.getNombre());

        for (int i = 0; i < padre.dlmLineasPedido.size(); i++) {
            LineaPedido lp = (LineaPedido) padre.dlmLineasPedido.getElementAt(i);
            dlmCestaDefinitiva.addElement(lp);
        }

        float total = 0;
        for (int i = 0; i < dlmCestaDefinitiva.size(); i++) {
            LineaPedido lp = (LineaPedido) dlmCestaDefinitiva.getElementAt(i);
            total = total + (lp.getArticuloLinea().getPrecio() * lp.getCantidad());
        }
        tf_total.setText(String.valueOf(total));
        tf_total.setEditable(false);

        ArrayList<TarjetaBancaria> atb = TarjetaBancaria.consultarTarjetasUsuario(usuario);
        if (!atb.isEmpty()) {
            dlmTarjetas.addAll(atb);
        } else {
            JOptionPane.showMessageDialog(this, "Aún no dispone de ninguna tarjeta bancaria asociada a su cuenta");
        }

        lst_CestaDefinitiva.updateUI();
        lst_TarjetasDisponibles.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_CestaDefinitiva = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_TarjetasDisponibles = new javax.swing.JList<>();
        bt_aniadirNuevaTarjeta = new javax.swing.JButton();
        bt_realizarPedido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_socioCliente = new javax.swing.JTextField();
        bt_volverAtras = new javax.swing.JButton();
        tf_total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Resumen de su carrito:");

        lst_CestaDefinitiva.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lst_CestaDefinitiva);

        jLabel2.setText("Selecciona una tarjeta de crédito:");

        lst_TarjetasDisponibles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_TarjetasDisponibles);

        bt_aniadirNuevaTarjeta.setText("AÑADIR NUEVA TARJETA");
        bt_aniadirNuevaTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_aniadirNuevaTarjetaActionPerformed(evt);
            }
        });

        bt_realizarPedido.setText("REALIZAR PEDIDO");
        bt_realizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_realizarPedidoActionPerformed(evt);
            }
        });

        jLabel3.setText("PAGO DEL PEDIDO:");

        jLabel9.setText("Usuario:");

        tf_socioCliente.setDisabledTextColor(new java.awt.Color(200, 20, 20));
        tf_socioCliente.setEnabled(false);

        bt_volverAtras.setText("VOLVER ATRÁS");
        bt_volverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverAtrasActionPerformed(evt);
            }
        });

        tf_total.setText("jTextField1");

        jLabel4.setText("TOTAL:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_socioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(bt_realizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_aniadirNuevaTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(bt_volverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_socioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(64, 64, 64)
                        .addComponent(bt_aniadirNuevaTarjeta)
                        .addGap(18, 18, 18)
                        .addComponent(bt_realizarPedido))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_volverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_total)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_volverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverAtrasActionPerformed
        // TODO add your handling code here:
        VentanaClientes vc = new VentanaClientes(usuario);
        for (int i = 0; i < dlmCestaDefinitiva.size(); i++) {
            vc.dlmLineasPedido.add(i, dlmCestaDefinitiva.getElementAt(i));
        }
        this.dispose();
        vc.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_bt_volverAtrasActionPerformed

    private void bt_realizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_realizarPedidoActionPerformed
        // TODO add your handling code here:
        Date fecha = new Date();
        ArrayList<LineaPedido> lineasDePedido = new ArrayList<>();
        for (int i = 0; i < dlmCestaDefinitiva.getSize(); i++) {
            lineasDePedido.add(i,(LineaPedido) dlmCestaDefinitiva.getElementAt(i));
        }

        ArrayList<Ruta> rutas = Ruta.obtenerRutas();
        int numRuta = Ruta.obtenerIdRutaSocio(rutas, usuario);
        DatabaseConnection db = new DatabaseConnection();
        Pedido pedido = new Pedido(fecha, Float.parseFloat(tf_total.getText()), lineasDePedido, usuario.getIdSocio(), numRuta);

        if (dlmTarjetas.size() == 0) {
            JOptionPane.showMessageDialog(this, "No puedes realizar el pedido si no tienes una tarjeta con la que realizar el pago");
        } else {
            if (lst_TarjetasDisponibles.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Debes de seleccionar una tarjeta con la que realizar el pago");
            } else {
                if (numRuta == 0) {
                    JOptionPane.showMessageDialog(this, "Lo sentimos, nuestra empresa no podrá repartir tu pedido por temas de transporte");
                } else {
                    db.aniadirPedidoBBDD(pedido);
                    pedido.setIdPedido(Pedido.obtenerUltimoPedido());
                    LineaPedido.aniadirLineasDelPedido(pedido);
                }
            }
        }
    }//GEN-LAST:event_bt_realizarPedidoActionPerformed

    private void bt_aniadirNuevaTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_aniadirNuevaTarjetaActionPerformed
        // TODO add your handling code here:
        VentanaNuevaTarjeta vnt = new VentanaNuevaTarjeta(this, rootPaneCheckingEnabled, this.usuario);
        vnt.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_bt_aniadirNuevaTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPagoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPagoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPagoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPagoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaPagoPedido dialog = new VentanaPagoPedido(new javax.swing.JFrame(), true, usuario);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_aniadirNuevaTarjeta;
    private javax.swing.JButton bt_realizarPedido;
    private javax.swing.JButton bt_volverAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lst_CestaDefinitiva;
    private javax.swing.JList<String> lst_TarjetasDisponibles;
    private javax.swing.JTextField tf_socioCliente;
    private javax.swing.JTextField tf_total;
    // End of variables declaration//GEN-END:variables
}
