/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tacondeoro;

import javax.swing.JOptionPane;

/**
 *
 * @author usutarde
 */
public class VentanaInicioSesion extends javax.swing.JDialog {
    private VentanaPrincipal padre;
    private Socio socio;

    /**
     * Creates new form InicioRegistro
     */
    public VentanaInicioSesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        padre = (VentanaPrincipal) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        btt_iniciarSesion = new javax.swing.JButton();
        btt_AbrirVentanaRegistro = new javax.swing.JButton();
        tf_nombreUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_contraseña = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_contraseña1 = new javax.swing.JTextField();
        cb_adminMozo = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btt_volverAtras = new javax.swing.JToggleButton();

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 105, Short.MAX_VALUE)
                .addComponent(jRadioButton1))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(2, 2, 2));

        btt_iniciarSesion.setBackground(new java.awt.Color(129, 129, 129));
        btt_iniciarSesion.setForeground(new java.awt.Color(255, 195, 0));
        btt_iniciarSesion.setText("Iniciar Sesión");
        btt_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_iniciarSesionActionPerformed(evt);
            }
        });

        btt_AbrirVentanaRegistro.setBackground(new java.awt.Color(129, 129, 129));
        btt_AbrirVentanaRegistro.setForeground(new java.awt.Color(255, 195, 0));
        btt_AbrirVentanaRegistro.setText("Darse de alta");
        btt_AbrirVentanaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_AbrirVentanaRegistroActionPerformed(evt);
            }
        });

        tf_nombreUsuario.setBackground(new java.awt.Color(202, 202, 202));
        tf_nombreUsuario.setForeground(new java.awt.Color(255, 195, 0));
        tf_nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(2, 2, 2));
        jLabel1.setForeground(new java.awt.Color(255, 195, 0));
        jLabel1.setText("Correo Electronico");

        tf_contraseña.setBackground(new java.awt.Color(203, 203, 203));
        tf_contraseña.setForeground(new java.awt.Color(203, 203, 203));
        tf_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_contraseñaActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(2, 2, 2));
        jLabel2.setForeground(new java.awt.Color(255, 195, 0));
        jLabel2.setText("Contraseña");

        jLabel3.setBackground(new java.awt.Color(2, 2, 2));
        jLabel3.setForeground(new java.awt.Color(255, 195, 0));
        jLabel3.setText("Codigo Admin/Mozo");

        tf_contraseña1.setEditable(false);
        tf_contraseña1.setBackground(new java.awt.Color(203, 203, 203));
        tf_contraseña1.setForeground(new java.awt.Color(203, 203, 203));
        tf_contraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_contraseña1ActionPerformed(evt);
            }
        });

        cb_adminMozo.setText("Admin/Mozo");
        cb_adminMozo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_adminMozoMouseClicked(evt);
            }
        });

        jLabel4.setText("¿Aún no te has registrado?");

        btt_volverAtras.setText("Volver atrás");
        btt_volverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_volverAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(cb_adminMozo)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_contraseña1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombreUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_contraseña, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btt_iniciarSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(btt_volverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(124, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(btt_AbrirVentanaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_adminMozo))
                .addGap(25, 25, 25)
                .addComponent(btt_iniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(btt_volverAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_AbrirVentanaRegistro)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_iniciarSesionActionPerformed
        DatabaseConnection a = new DatabaseConnection();
       
        socio = a.iniciarSesion(tf_nombreUsuario.getText(), tf_contraseña.getText());
        if (socio.getCorreoe().equalsIgnoreCase(tf_nombreUsuario.getText())) {
            VentanaClientes c = new VentanaClientes(socio);
            c.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "El correo o la contraseña son incorrectos");
        }
    }//GEN-LAST:event_btt_iniciarSesionActionPerformed

    public void limpiar(){
        tf_nombreUsuario.setText("");
        tf_contraseña.setText("");
    }
    private void tf_nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreUsuarioActionPerformed

    private void tf_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_contraseñaActionPerformed

    private void btt_AbrirVentanaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_AbrirVentanaRegistroActionPerformed
        VentanaPrincipal b = new VentanaPrincipal();
        VentanaRegistro a = new VentanaRegistro(b, rootPaneCheckingEnabled);
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_btt_AbrirVentanaRegistroActionPerformed

    private void tf_contraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_contraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_contraseña1ActionPerformed

    private void cb_adminMozoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_adminMozoMouseClicked
        if (cb_adminMozo.isSelected()) {
            tf_contraseña1.setEditable(true);
        } else {
            tf_contraseña1.setEditable(false);
        }
    }//GEN-LAST:event_cb_adminMozoMouseClicked

    private void btt_volverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_volverAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btt_volverAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaInicioSesion dialog = new VentanaInicioSesion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_AbrirVentanaRegistro;
    private javax.swing.JButton btt_iniciarSesion;
    private javax.swing.JToggleButton btt_volverAtras;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb_adminMozo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_contraseña1;
    private javax.swing.JTextField tf_nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
