/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tacondeoro;

import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Arturo
 */
public class VentanaClientes extends javax.swing.JFrame {
    Connection c = null;
    DefaultListModel dlmArticulos;
    DefaultListModel dlmLineasPedido;
    private static Socio usuario;

    /**
     * Creates new form VentanaClientes
     * @param 
     */
    public VentanaClientes(Socio socio) {
        initComponents();
        this.setLocationRelativeTo(null);
        dlmArticulos = new DefaultListModel();
        dlmLineasPedido = new DefaultListModel();
        lst_Articulos.setModel(dlmArticulos);
        lst_lineasPedido.setModel(dlmLineasPedido);
        usuario = socio;
        tf_socioCliente.setText(usuario.getNombre());
        DatabaseConnection db = new DatabaseConnection();
        c = db.getConexion();
        ArrayList<Articulo> ar = Articulo.obtenerArticulos();
        dlmArticulos.addAll(ar);
        tf_total.setEditable(false);
    }

    public JTextField getTf_total() {
        return tf_total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoGradiente(Color.decode("#115ad3"), Color.decode("#11d0d3"));
        cb_CampaniaOtonioInvierno = new javax.swing.JCheckBox();
        cb_CampaniaPrimaveraVerano = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_Articulos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lst_lineasPedido = new javax.swing.JList<>();
        btt_aniadirAlCarrito = new javax.swing.JButton();
        btt_tramitarPedido = new javax.swing.JButton();
        btt_borrarDelCarrito = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_Cantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_Bolsos = new javax.swing.JCheckBox();
        cb_Complementos = new javax.swing.JCheckBox();
        cb_Zapatos = new javax.swing.JCheckBox();
        tf_Talla = new javax.swing.JTextField();
        cbb_anioTemporada = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_socioCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_CampaniaOtonioInvierno.setText("Otoño / Invierno");
        cb_CampaniaOtonioInvierno.setOpaque(false);
        cb_CampaniaOtonioInvierno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CampaniaOtonioInviernoActionPerformed(evt);
            }
        });

        cb_CampaniaPrimaveraVerano.setText("Primavera / Verano");
        cb_CampaniaPrimaveraVerano.setOpaque(false);
        cb_CampaniaPrimaveraVerano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CampaniaPrimaveraVeranoActionPerformed(evt);
            }
        });

        lst_Articulos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_Articulos.setAutoscrolls(false);
        jScrollPane2.setViewportView(lst_Articulos);

        jLabel1.setText("ARTÍCULOS:");

        jLabel5.setText("CANTIDAD:");

        lst_lineasPedido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Linea Pedido 1", "Linea Pedido 2", "Linea Pedido 3", "Linea Pedido 4", "Linea Pedido 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lst_lineasPedido);

        btt_aniadirAlCarrito.setBackground(new java.awt.Color(0, 51, 51));
        btt_aniadirAlCarrito.setForeground(new java.awt.Color(255, 204, 0));
        btt_aniadirAlCarrito.setText("AÑADIR AL CARRITO");
        btt_aniadirAlCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_aniadirAlCarritoActionPerformed(evt);
            }
        });

        btt_tramitarPedido.setBackground(new java.awt.Color(0, 51, 51));
        btt_tramitarPedido.setForeground(new java.awt.Color(255, 204, 0));
        btt_tramitarPedido.setText("TRAMITAR PEDIDO");
        btt_tramitarPedido.setBorder(new javax.swing.border.MatteBorder(null));
        btt_tramitarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_tramitarPedidoActionPerformed(evt);
            }
        });

        btt_borrarDelCarrito.setBackground(new java.awt.Color(0, 51, 51));
        btt_borrarDelCarrito.setForeground(new java.awt.Color(255, 204, 0));
        btt_borrarDelCarrito.setText("ELIMINAR DEL CARRITO");
        btt_borrarDelCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_borrarDelCarritoActionPerformed(evt);
            }
        });

        jLabel6.setText("TALLA:");

        jLabel2.setText("CARRITO:");

        jLabel3.setText("TOTAL DE PEDIDO:");

        cb_Bolsos.setText("Bolsos");
        cb_Bolsos.setOpaque(false);
        cb_Bolsos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_BolsosActionPerformed(evt);
            }
        });

        cb_Complementos.setText("Complementos");
        cb_Complementos.setOpaque(false);
        cb_Complementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ComplementosActionPerformed(evt);
            }
        });

        cb_Zapatos.setText("Zapatos");
        cb_Zapatos.setOpaque(false);
        cb_Zapatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ZapatosActionPerformed(evt);
            }
        });

        cbb_anioTemporada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "2021", "2022", "2023" }));
        cbb_anioTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_anioTemporadaActionPerformed(evt);
            }
        });

        jLabel4.setText("Año Temporada:");

        jLabel7.setText("Temporadas:");

        jLabel8.setText("Tipo de artículo:");

        tf_socioCliente.setDisabledTextColor(new java.awt.Color(200, 20, 20));
        tf_socioCliente.setEnabled(false);

        jLabel9.setText("Usuario:");

        jLabel10.setText("FILTROS:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_socioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_Complementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_Bolsos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_CampaniaPrimaveraVerano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_CampaniaOtonioInvierno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_anioTemporada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_Zapatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_Talla, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(tf_Cantidad))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btt_borrarDelCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(btt_aniadirAlCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_total)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(btt_tramitarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_socioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(tf_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(tf_Talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btt_aniadirAlCarrito)
                                        .addGap(18, 18, 18)
                                        .addComponent(btt_borrarDelCarrito)
                                        .addGap(125, 125, 125))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(12, 12, 12)
                                .addComponent(btt_tramitarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_CampaniaPrimaveraVerano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_CampaniaOtonioInvierno)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbb_anioTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_Zapatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_Bolsos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_Complementos)
                        .addGap(37, 37, 37))))
        );

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_CampaniaOtonioInviernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CampaniaOtonioInviernoActionPerformed
        // TODO add your handling code here:
        comprobarFiltros();
    }//GEN-LAST:event_cb_CampaniaOtonioInviernoActionPerformed

    private void cb_CampaniaPrimaveraVeranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CampaniaPrimaveraVeranoActionPerformed
        // TODO add your handling code here:
        comprobarFiltros();
    }//GEN-LAST:event_cb_CampaniaPrimaveraVeranoActionPerformed

    private void btt_aniadirAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_aniadirAlCarritoActionPerformed
        // TODO add your handling code here:
        int indice = lst_Articulos.getSelectedIndex();
        float total = 0;

        if (indice == -1 && tf_Cantidad.getText().equalsIgnoreCase("") || indice == -1 || tf_Cantidad.getText().equalsIgnoreCase("") || tf_Cantidad.getText().equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(this, "Para añadir un artículo al carrito debes seleccionarlo y escribir la cantidad deseada (mayor que 0)");
        } else {
            LineaPedido a = new LineaPedido((Articulo) dlmArticulos.get(indice), Integer.parseInt(tf_Cantidad.getText()));
            Articulo b = (Articulo) dlmArticulos.get(indice);
            dlmLineasPedido.addElement(a);

            if (dlmLineasPedido.size() > 1) {
                for (int i = 0; i < dlmLineasPedido.size(); i++) {
                    LineaPedido x = (LineaPedido) dlmLineasPedido.getElementAt(i);
                    total = total + (x.getArticuloLinea().getPrecio() * x.getCantidad());
                }

                for (int i = 0; i < dlmLineasPedido.size(); i++) {
                    LineaPedido x = (LineaPedido) dlmLineasPedido.getElementAt(i);
                    for (int j = 0; j < dlmLineasPedido.size(); j++) {
                        LineaPedido c = (LineaPedido) dlmLineasPedido.getElementAt(j);
                        if (!(i == j) && x.getArticuloLinea().getNombre().equals(c.getArticuloLinea().getNombre())) {
                            c.setCantidad(c.getCantidad()+x.getCantidad());
                            dlmLineasPedido.removeElement(x);
                            lst_lineasPedido.updateUI();
                        }
                    }
                }
            } else if (dlmLineasPedido.size() == 1) {
                total = (b.getPrecio() * Integer.parseInt(tf_Cantidad.getText()));
            }

            tf_total.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_btt_aniadirAlCarritoActionPerformed

    private void btt_tramitarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_tramitarPedidoActionPerformed
        // TODO add your handling code here:
        if (dlmLineasPedido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Para tramitar pedido tiene que añadir artículos en la cesta");
        } else {
            this.dispose();
            VentanaPagoPedido vcc = new VentanaPagoPedido(this,rootPaneCheckingEnabled, this.usuario);
            vcc.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_btt_tramitarPedidoActionPerformed

    private void btt_borrarDelCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_borrarDelCarritoActionPerformed
        // TODO add your handling code here:
        int indice = lst_lineasPedido.getSelectedIndex();
        float total = 0;

        if (indice == -1 ) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un artículo a eliminar");
        } else {
            LineaPedido li = (LineaPedido) dlmLineasPedido.getElementAt(indice);
            float precioanterior = li.getCantidad() * li.getArticuloLinea().getPrecio();
            float f = Float.parseFloat(tf_total.getText()) - precioanterior;
            tf_total.setText(String.valueOf(f));
            dlmLineasPedido.removeElementAt(indice);
        }
    }//GEN-LAST:event_btt_borrarDelCarritoActionPerformed

    private void cb_BolsosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_BolsosActionPerformed
        // TODO add your handling code here:
        comprobarFiltros();
    }//GEN-LAST:event_cb_BolsosActionPerformed

    private void cb_ComplementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ComplementosActionPerformed
        // TODO add your handling code here:
        comprobarFiltros();
    }//GEN-LAST:event_cb_ComplementosActionPerformed

    private void cb_ZapatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ZapatosActionPerformed
        // TODO add your handling code here:
        comprobarFiltros();
    }//GEN-LAST:event_cb_ZapatosActionPerformed

    private void cbb_anioTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_anioTemporadaActionPerformed
        // TODO add your handling code here:
        comprobarFiltros();
    }//GEN-LAST:event_cbb_anioTemporadaActionPerformed

    private void comprobarFiltros() {
        ArrayList<Zapato> za = Zapato.obtenerZapatos();
        ArrayList<Bolso> bo = Bolso.obtenerBolsos();
        ArrayList<Complemento> co = Complemento.obtenerComplementos();

        boolean filtroZapatos = cb_Zapatos.isSelected();
        boolean filtroBolsos = cb_Bolsos.isSelected();
        boolean filtroComplementos = cb_Complementos.isSelected();
        boolean filtroCampaniaPV = cb_CampaniaPrimaveraVerano.isSelected();
        boolean filtroCampaniaOI = cb_CampaniaOtonioInvierno.isSelected();
        int anioSeleccionado = cbb_anioTemporada.getSelectedIndex();
        dlmArticulos.clear();

        if (!filtroZapatos && !filtroBolsos && !filtroComplementos || filtroZapatos && filtroBolsos && filtroComplementos) {
            dlmArticulos.addAll(za);
            dlmArticulos.addAll(bo);
            dlmArticulos.addAll(co);
            cb_CampaniaPrimaveraVerano.setEnabled(true);
            cb_CampaniaOtonioInvierno.setEnabled(true);
            cbb_anioTemporada.setEnabled(true);
            lst_Articulos.updateUI();
        } else if (filtroZapatos || filtroBolsos || filtroComplementos) {
            ocultarTemporadaAnio();
            if (filtroZapatos) {
                dlmArticulos.addAll(za);
            }
            if (filtroBolsos) {
                dlmArticulos.addAll(bo);
            }
            if (filtroComplementos) {
                dlmArticulos.addAll(co);
            }
            lst_Articulos.updateUI();
        }

        if (!filtroCampaniaPV && !filtroCampaniaOI || filtroCampaniaPV && filtroCampaniaOI) {
            cb_Zapatos.setEnabled(true);
            cb_Bolsos.setEnabled(true);
            cb_Complementos.setEnabled(true);
            lst_Articulos.updateUI();
        } else if (filtroCampaniaPV || filtroCampaniaOI) {
            ocultarArticulosAnio();
            if (filtroCampaniaPV) {
                dlmArticulos.clear();
                ArrayList<Object> opv = Campania.obtenerTemporada("Primavera / Verano");
                dlmArticulos.addAll(opv);
            }
            if (filtroCampaniaOI) {
                dlmArticulos.clear();
                ArrayList<Object> ooi = Campania.obtenerTemporada("Otoño / Invierno");
                dlmArticulos.addAll(ooi);
            }
            lst_Articulos.updateUI();
        }

        if (anioSeleccionado != 0) {
            ocultarTemporadaArticulos();
            dlmArticulos.clear();
            ArrayList<Object> oa = Campania.obtenerAnio(2021 + anioSeleccionado - 1);
            dlmArticulos.addAll(oa);
            lst_Articulos.updateUI();
        }
        
    }

    private void ocultarTemporadaAnio() {
        cb_CampaniaPrimaveraVerano.setEnabled(false);
        cb_CampaniaOtonioInvierno.setEnabled(false);
        cbb_anioTemporada.setEnabled(false);
    }

    private void ocultarTemporadaArticulos() {
        cb_Zapatos.setEnabled(false);
        cb_Bolsos.setEnabled(false);
        cb_Complementos.setEnabled(false);
        cb_CampaniaPrimaveraVerano.setEnabled(false);
        cb_CampaniaOtonioInvierno.setEnabled(false);
    }

    private void ocultarArticulosAnio() {
        cb_Zapatos.setEnabled(false);
        cb_Bolsos.setEnabled(false);
        cb_Complementos.setEnabled(false);
        cbb_anioTemporada.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    private VentanaClientes() {
        
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_aniadirAlCarrito;
    private javax.swing.JButton btt_borrarDelCarrito;
    private javax.swing.JButton btt_tramitarPedido;
    private javax.swing.JCheckBox cb_Bolsos;
    private javax.swing.JCheckBox cb_CampaniaOtonioInvierno;
    private javax.swing.JCheckBox cb_CampaniaPrimaveraVerano;
    private javax.swing.JCheckBox cb_Complementos;
    private javax.swing.JCheckBox cb_Zapatos;
    private javax.swing.JComboBox<String> cbb_anioTemporada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> lst_Articulos;
    private javax.swing.JList<String> lst_lineasPedido;
    private javax.swing.JTextField tf_Cantidad;
    private javax.swing.JTextField tf_Talla;
    private javax.swing.JTextField tf_socioCliente;
    private javax.swing.JTextField tf_total;
    // End of variables declaration//GEN-END:variables
}
